### PR TITLE
Switch distribution from Module::Build to ExtUtils::MakeMaker

### PR DESCRIPTION
**Pull request by karenetheridge**
This PR switches the tooling from Module::Build to ExtUtils::MakeMaker.

Neil Bowers described the general concept of the CPAN River here -- http://neilb.org/2015/04/20/river-of-cpan.html

As it turns out, Module::Pluggable sits very high on the river, because it has no non-core dependencies, used to be dual-life, and it is used by a tremendous number of distributions, many of which themselves are quite important: http://deps.cpantesters.org/depended-on-by.pl?module=Module::Pluggable (e.g. App::Cmd, Catalyst, Dist::Zilla etc).

We (the Perl Toolchain Gang) have started looking closely at the top end of the river and considering ways in which we can clean it up. One thing we've been doing which helps out earlier versions of perl, as well as speeding up all installations, is removing unnecessary dependencies on Module::Build, which itself was removed from core last year (see http://www.dagolden.com/index.php/2140/paying-respect-to-modulebuild/). Presently, Module::Pluggable is the fourth-highest distribution on the river which uses MB, and its removal there will help move Module::Build's position considerably down-river.

I hope this set of changes is more satisfactory to you. I'm happy to refine further, or answer any questions.

### CODE REVIEW

**Comment by simonwistow** [comment]
I'm going to look at some other bugs and pull requests and try and get a release out this week.

**Comment by simonwistow** [comment]
Hi Karen - I actually used bits of your pull request and also this one simonwistow/Module-Pluggable#9

Into [this branch](/simonwistow/Module-Pluggable/tree/use-extutils-makemaker)

Can you check to see my branch works for you and I'll merge and deploy.

**Comment by simonwistow** [comment]
Also: because of another branch I had to add in support for an optional module. 

It's been a while since I've used EUMM so I'm not sure if I've done it right. If you could double check that I'd be very grateful.

**Comment by karenetheridge** [comment]
As commented in #9, I've rebased this PR to include the new changes in master, and brought in the bits from your commit and @moto-timo's that I missed.

**Comment by simonwistow** [comment]
Released to CPAN as version 5.2

**Comment by simonwistow** [comment]
Thanks for all your help on everything - sorry for being a bit lax

**Comment by karenetheridge** [comment]
Hooray, thank you very much!

**Comment by moto-timo** [comment]
Yay!
One down...oh soooooo many to go :)

**Pull request closed without merging**
