### PR TITLE
Add before_instantiate and after_instantiate hooks

### PR DESCRIPTION
**Pull request by djzort**
- Both hooks added in Object.pm
- Added pod in Pluggable.pm
- The above is in order of execution
- Added some basic tests to ensure the hooks fire
- Also removed some dead whitespace

### CODE REVIEW

**Comment by djzort** [comment]
I will leave updating changelog, bumping versions and what not to the author/maintainer

**Comment by djzort** [comment]
any thoughts or feedback?

**Comment by simonwistow** [comment]
On Mon, Sep 07, 2015 at 10:49:48PM -0700, Dean Hamstead said:
> any thoughts or feedback?

So sorry - last week was crazy. Will try and get to it today.

**Comment by djzort** [comment]
ping?

**Comment by djzort** [comment]
ping?

**Comment by djzort** [comment]
Nice. Only 4 years later :)

**Pull request merged**
